site_name: Colchian
nav:
  - Home: index.md
  - 'Getting Started': getting_started.md
  - 'Colchian class': colchian.md
  - 'Examples': examples.md
  - 'Wildcards': wildcards.md
  - About: about.md
theme:
  name: readthedocs
  features:
    - content.code.copy
markdown_extensions:
  - admonition
plugins:
  - search
  - mkdocstrings
dependecies:
- pip:
    - jinja2<3.1.0
